name: Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Test Docker build
      run: |
        docker build -t barel-test .devcontainer/
        
    - name: Test docker-compose
      run: |
        docker-compose config
        
    - name: Check script permissions
      run: |
        test -x scripts/init-project.sh
        test -x scripts/generate-keys.sh
        test -x scripts/check-health.sh
        test -x scripts/db-backup.sh
        test -x scripts/db-restore.sh
        test -x quick-start.sh